### ISSUE TITLE
Java Client Library for ROS 2

### ISSUE THREAD

**Issue by wilcobonestroo** [nielstiben/openTCS-NeNa#4]
Hi Niels,

It is really good to see that you are working on the OpenTCS NeNa project and have updated your work for Foxy. I see that you have switched to IHMC Java communication for the ROS 2 connection, instead of RCL Java. Can you explain why you did this and what the consequences are?

Ps. Maybe you should consider renaming the project as it is becoming a general OpenTCS ROS 2 bridge.

Wilco

**Comment by nielstiben** [comment]
Hello Wilco, 
Thank you for reaching out. Surely, I can elaborate on my decision to switch from RCLJava to IHMC:

* RCLJava is not yet updated for ROS 2 Foxy. Experiments for using the latest RCLJava version (targeting ROS 2 Dashing) for Foxy have been done, but it did work due to small differences in several message types.
* The IHMC is completely stand-alone and therefore not dependent on a local ROS 2 installation on your system. This makes it much easier to install the OpenTCS-NeNa software and eliminates the need to build the OpenTCS-NeNa software on your machine.
This also means that it is no longer needed to hard-code your ROS 2 workspace in the OpenTCS-NeNa build script.
Due to IHMC its independence, this software should now also work on other operating systems, such as Windows. However, this has not been tested.
*  The previous OpenTCS-NeNa release (1.1) used OpenTCS 4.17 which uses Java 8. The IHMC library used to be incompatible with Java 8.
This OpenTCS-NeNa release (2.0) uses OpenTCS 5.0 which uses Java 13, making it now compatible with the IHMC library.`
The biggest advantage of the IHMC library, its independence, is also its largest drawback.
Applications such as ROS2 RQT, will no longer recognize the OpenTCS node because it is now
seen as an external entity.

I will consider renaming this project on a next release. I agree with you that the software is in fact a general OpenTCS ROS 2 bridge.

Niels
